version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME}-php
        volumes:
            - './app:/var/www/html'
            - './config/php/php.ini:/usr/local/etc/php/php.ini'
        restart: always
        depends_on:
            - database
    nginx:
        image: nginx
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - ./app:/var/www/html
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - ./config/nginx/log:/var/log/nginx
        restart: unless-stopped
        depends_on:
            - php
    database:
        image: mysql:8.0
        volumes:
            - ./config/db/dbdata:/var/lib/mysql
            - ./config/db/my.cnf:/etc/mysql/conf.d/my.cnf
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
        restart: always